# Generated by Django 2.2.1 on 2019-05-13 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ManufactorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Showroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.CharField(max_length=3550)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank='True', upload_to='all_image')),
                ('tagline', models.CharField(max_length=100)),
                ('mileage', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('model', models.IntegerField()),
                ('status', models.BooleanField()),
                ('transmission', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=50)),
                ('price', models.IntegerField()),
                ('horse_power', models.IntegerField()),
                ('propellant', models.CharField(max_length=100)),
                ('manufactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Manufactor')),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_showroom', to='apis.Showroom')),
            ],
        ),
    ]
