# Generated by Django 2.2.1 on 2019-05-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_auto_20190513_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='horse_power',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
